### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by mattmassicotte**
I was pleasantly surprised to find that a Makefile was already present in the project! However, it uses a slightly older and less-generic version.

This PR updates it to be nearly identical to the standardized version. The one difference is because of the "go-work" repo name, vs "gowork" language name, it has to be manually tweaked. Not a huge deal.

### CODE REVIEW

**Comment by omertuc** [comment]
This repo/makefile is just a clone of https://github.com/camdencheek/tree-sitter-go-mod - so perhaps you want to get this merged there first

**Comment by omertuc** [comment]
Oh I see [you've already done that a while ago](https://github.com/camdencheek/tree-sitter-go-mod/pull/4)

**Comment by mattmassicotte** [comment]
Ah, do you periodically pull in changes made to that repo? I just assumed this was just based on go-mod, but was going to remain independent now.

**Comment by omertuc** [comment]
> Ah, do you periodically pull in changes made to that repo? 

Not really, but I probably should do that manually once in a while if they're applicable here as well

> I just assumed this was just based on go-mod, but was going to remain independent now.

It is independent, it's just that I didn't write the original makefile so I don't fully understand its purpose / your changes to it, so I wanted to see a similar thing being done to the go mod repo to make me confident it should be done/merged here as well

**Comment by mattmassicotte** [comment]
That makes total sense!

The purpose of the makefile is to automate packaging the parser up into static/dynamic libraries for easy use with languages that can consume C-based dependencies.

It was a long process getting it setup, which I did with the help of the tree-sitter maintainers. I've now just got myself in the unenviable position of trying to get it set up and working in all parsers.

**Comment by omertuc** [comment]
Ah I see, good luck and thank you for that effort

**Pull request merged**
